### ISSUE TITLE
FreeBSD warnings

### ISSUE THREAD

**Issue by jungle-boogie** [irontec/sngrep#91] opened 2016-02-03 05:25 UTC
Hello,

In preperation to make `sngrep` a port/package on FreeBSD, I'd like to enable a few extra config options I haven't tested before and noticed some compiler warnings.

config:
```
./configure --with-pcre --with-openssl --enable-eep --enable-ipv6 \
CFLAGS=-I/usr/local/include LDFLAGS=-L/usr/local/lib
```

Full make:
```
# make
Making all in src
make  all-am
  CC       capture.o
  CC       capture_eep.o
capture_eep.c:345:32: warning: implicit conversion from 'unsigned int' to 'u_int16_t' (aka 'unsigned short') changes value from 369098752 to 0 [-Wconstant-conversion]
        src_ip6.chunk.length = htonl(sizeof(src_ip6));
                             ~ ^~~~~~~~~~~~~~~~~~~~~~
/usr/include/netinet/in.h:117:18: note: expanded from macro 'htonl'
#define htonl(x)        __htonl(x)
                        ^~~~~~~~~~
/usr/include/x86/endian.h:126:20: note: expanded from macro '__htonl'
#define __htonl(x)      __bswap32(x)
                        ^~~~~~~~~~~~
/usr/include/x86/endian.h:78:6: note: expanded from macro '__bswap32'
            __bswap32_gen((__uint32_t)(x)) : __bswap32_var(x))
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/x86/endian.h:68:47: note: expanded from macro '__bswap32_gen'
        (((__uint32_t)__bswap16((x) & 0xffff) << 16) | __bswap16((x) >> 16))
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
capture_eep.c:351:32: warning: implicit conversion from 'unsigned int' to 'u_int16_t' (aka 'unsigned short') changes value from 369098752 to 0 [-Wconstant-conversion]
        dst_ip6.chunk.length = htonl(sizeof(dst_ip6));
                             ~ ^~~~~~~~~~~~~~~~~~~~~~
/usr/include/netinet/in.h:117:18: note: expanded from macro 'htonl'
#define htonl(x)        __htonl(x)
                        ^~~~~~~~~~
/usr/include/x86/endian.h:126:20: note: expanded from macro '__htonl'
#define __htonl(x)      __bswap32(x)
                        ^~~~~~~~~~~~
/usr/include/x86/endian.h:78:6: note: expanded from macro '__bswap32'
            __bswap32_gen((__uint32_t)(x)) : __bswap32_var(x))
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/x86/endian.h:68:47: note: expanded from macro '__bswap32_gen'
        (((__uint32_t)__bswap16((x) & 0xffff) << 16) | __bswap16((x) >> 16))
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
2 warnings generated.
  CC       capture_openssl.o
  CC       sip.o
  CC       sip_call.o
  CC       sip_msg.o
  CC       sip_attr.o
  CC       main.o
  CC       option.o
  CC       group.o
  CC       filter.o
  CC       keybinding.o
  CC       media.o
  CC       setting.o
  CC       rtp.o
  CC       util.o
  CC       vector.o
  CC       ui_manager.o
  CC       ui_call_list.o
  CC       ui_call_flow.o
  CC       ui_call_raw.o
  CC       ui_stats.o
  CC       ui_filter.o
  CC       ui_save.o
  CC       ui_msg_diff.o
  CC       ui_column_select.o
  CC       ui_settings.o
  CCLD     sngrep
Making all in config
Making all in doc
Making all in tests
```

Is this something that can be corrected?

**Comment by Kaian** [comment] 2016-02-03 10:20
Yes, it can be fixed!

The eep source is taken directly from the sipcapture/hep-c example, which in fact have the same error.

https://github.com/sipcapture/hep-c/blob/master/core_hep.c#L174

The problem is that, for IPv6 we are using the function htonl insted of htons like in IPv4.

Thanks for reporting!

**Comment by Kaian** [comment] 2016-02-03 10:25
It should be fixed now.
Could you give it a try to latest `master` commit?

**Closed** 2016-02-03 10:25 UTC

**Comment by jungle-boogie** [comment] 2016-02-03 14:47
> It should be fixed now.

Confirmed! Thank you for your assistance.
