### ISSUE TITLE
Improve TCP parsing

### ISSUE THREAD

**Issue by nshopik** [irontec/sngrep#85] opened 2016-01-15 12:37 UTC
TCP handling currently aren't perfect and could miss packets if there is reassembly required, so sngprep will only show non reassembled messages, thus miss full callflow.

**Comment by Kaian** [comment] 2016-01-18 19:08
I have been debugging the pcap you provided (it really helps a lot) and it seems multiple packets are buffered before they are sent. This causes some troubles to sngrep TCP logic that is ready to handle each packet to be sent one by one without buffering, expecting all of them to have the TCP flag PSH (if not, segment is part of a not assembled packet).

Of course, this is not the proper way to handle TCP segments. The problem is that, the proper way should be adding each segment to a stream and check if the received data so far belongs to one or more SIP messages (most probably using the Content-Length header). 

This is not a trivial change: I must move part of the SIP parsing process to the capture packet logic, which will for sure affect performance (lots of people starts sngrep without command line capture filters) and breaks a bit the design of each layer.

I will keep it in mind, but this change requires recoding a lot :)

**Comment by nshopik** [comment] 2016-01-18 20:32
Since its will affect performance its probably wise not enabled scan TCP by default, when its done. You could set udp filter by default.

**Comment by Kaian** [comment] 2016-01-29 16:20
Hi @nshopik 

If you have the time, check if the `issue_85` branch parses all TCP packets you're handling.
I have tested it with the pcap you provided and it seems to print all messages.

Thanks!

**Comment by nshopik** [comment] 2016-02-01 08:51
looks good, no problem so far with TCP on `issue_85` branch

**Comment by nshopik** [comment] 2016-02-01 11:26
Futher testing shows that some calls may stuck in `IN CALL` state. These calls seems doesn't have BYE messages to finish off session.

**Comment by Kaian** [comment] 2016-02-01 16:38
From the test file you've sent me, I've seen that tcp reassembly was not working as expected because the segments was not sorted (due to a TCP retransmission). sngrep was adding the two segments, but in the wrong order, so the SIP payload parsed didn't detect those packets as SIP messages.

I've also merged some latest commits from `master` to `issue_85` branch, that prevent crashes for your test file :)

If you have the time, give it a try!

Thanks!

**Closed** 2016-02-02 10:34 UTC
Labels: bug
