### ISSUE TITLE
call flow viewer loss 200 OK and 180 ring

### ISSUE THREAD

**Issue by michael2009** [irontec/sngrep#141] opened 2016-08-30 14:38 UTC
call flow viewer loss 200 OK and 180 ring
mailed pcap file .

**Comment by Kaian** [comment] 2016-08-30 16:43
Thanks for reporting michael!!

The problem was that 200 OK and 180 Ringing have the **exact** same time, so the sorting function was not detecting the proper order of this messages to be displayed. They were in fact being captured, as the MsgCnt showed 7 messages, but the flow only displayed 6.

It should be fixed in latest commit.

**Comment by jungle-boogie** [comment] 2016-09-02 05:22
I think this commit broke things.

To test:
0) start sngrep
1) wait for some non-call traffic (options and register) to appear
2) select one
3) press enter
4) observe that you can scroll through the data
5) enter for raw view
6) escape
7) escape
8) with a registered end point, make a call
9) scroll to that line
10) press enter

Can you enter into the call details? Can you escape sngrep? Do you see anymore traffic on sngrep?

The case for me is that I see traffic prior to the call (steps 1-6, basically), but once I attempt to view the communication on the call setup packet, sngrep freezes. To terminate, I ssh in as a user and kill the process.

I rolled back to the commits below and sngrep works as expected.
good:
7c56e4ebbb83c2e8d5000a0ca08e3d8064c2855b
e643a4911b2cd49592b7bca0a7d8e9260e2faeda
d89397387ffee56a4baf7ee082f8f39289c91ed6

**Comment by Kaian** [comment] 2016-09-02 08:45
Hi @jungle-boogie 

Confirmed! This was not detected in offline mode, where I usually test the changes.
The problem seems to be an infinite loop while searching the next arrow. We compare timestamps in order to sort the arrows. After changing the time comparison function it seems every arrow's next arrow is itself :(

Thanks for the testing!

**Comment by jungle-boogie** [comment] 2016-09-02 16:27
That fixed it!

**Comment by michael2009** [comment] 2016-09-03 13:18
Good , fixed !!

**Comment by Kaian** [comment] 2016-09-05 09:28
Nice! Thanks both for testing!

**Closed by Kaian** 2016-09-05 09:28 UTC
Labels: bug
