### ISSUE TITLE
Segmentation fault during SIP call setup

### ISSUE THREAD

**Issue by blessendor** [irontec/sngrep#111] opened 2016-04-13 06:53 UTC
Debian GNU/Linux 8

sngrep exit with 'Segmentation fault' error during first SIP call setup.
 
[112364.652876] sngrep[14140]: segfault at 6fdf318e91a1 ip 00006fdf31dcb04e sp 00006fdf318e0da8 error 4 in libc-2.19.so[6fdf31d39000+1a2000]
[112364.653127] grsec: From XXX.XXX.XXX.XX: Segmentation fault occurred at 00006fdf318e91a1 in /usr/bin/sngrep[sngrep:14140] uid/euid:0/0 gid/egid:0/0, parent /bin/bash[bash:6342] uid/euid:0/0 gid/egid:0/0

Error does not appears if I run **sngrep -d eth0**, but **sngrep** without options - will be segfaulted.

```
ifconfig:

eth0      Link encap:Ethernet  HWaddr 00:11:4d:ad:fd:24
          inet addr:XX.XX.XX.XX  Bcast:XX.XX.XX.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:498046 errors:0 dropped:0 overruns:0 frame:0
          TX packets:483770 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:144675145 (137.9 MiB)  TX bytes:214635941 (204.6 MiB)
          Interrupt:16 Memory:d0400000-d0420000

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:3317121 errors:0 dropped:0 overruns:0 frame:0
          TX packets:3317121 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:814270549 (776.5 MiB)  TX bytes:814270549 (776.5 MiB)

tun0      Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
          inet addr:1.1.77.1  P-t-P:1.1.77.2  Mask:255.255.255.255
          UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:100
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
```

**Comment by Kaian** [comment] 2016-04-13 09:10
Hi @blessendor 

This is the kind of issue I want to fix before moving to any enhancement.

Are you using the debian jessie binary package or is your sngrep compiled from source?

If you can send me a pcap captured with any other capturing tool (ngrep, tcpdump, or so) so I can reproduce the crash I will help a lot to debug the problem.

Thanks for reporting!!

**Comment by blessendor** [comment] 2016-04-13 10:16
How I can send you pcap in private?

**Comment by Kaian** [comment] 2016-04-13 10:17
Send it to kaian@irontec.com :)
Thanks in advance!

**Comment by blessendor** [comment] 2016-04-13 10:18
Sent

**Comment by Kaian** [comment] 2016-04-13 10:30
Sadly my sngrep didn't crash :(
I'll try to figure where the problem could be

```
root@packages:~# dpkg -l | grep sngrep
ii  sngrep                               1.3.0+jessie                            amd64        Ncurses SIP Messages flow viewer

root@packages:~# sngrep -V
sngrep - 1.3.0
Copyright (C) 2013-2016 Irontec S.L.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
 * Compiled with OpenSSL support.
 * Compiled with Wide-character support.
 * Compiled with Perl Compatible regular expressions support.
 * Compiled with IPv6 support.
 * Compiled with EEP/HEP support.

Written by Ivan Alonso [aka Kaian]

root@packages:~# sngrep -I sip.pcap -N
Dialog count: 5
```

**Comment by blessendor** [comment] 2016-04-13 10:32
When I run **sngrep -I sip.pcap** it do not crash, yes.

**Comment by blessendor** [comment] 2016-04-13 10:34
ii  sngrep                         1.3.0+jessie                      amd64        Ncurses SIP Messages flow viewer

sngrep -V
sngrep - 1.3.0
Copyright (C) 2013-2016 Irontec S.L.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
 * Compiled with OpenSSL support.
 * Compiled with Wide-character support.
 * Compiled with Perl Compatible regular expressions support.
 * Compiled with IPv6 support.
 * Compiled with EEP/HEP support.

Written by Ivan Alonso [aka Kaian]

**Comment by Kaian** [comment] 2016-04-25 13:48
Hi!

I was still unable to reproduce this but I will like to get rid of crashes. If we are not able to get a pcap to reproduce an issue, maybe be can get a debugging backtrace.

If the crash can be easily reproduced, try installing the debug version of sngrep and a debugger (this will uninstall the _normal_ sngrep).

`apt-get update && apt-get install gdb sngrep-dbg`

Then run sngrep from the debugger with the crashing arguments, for example:

`gdb --ex 'set logging on' --ex run --args sngrep --device any`

When the crash occurs, the gdb prompt will appear `(gdb) `
Enter following commands:
```
info threads
thread apply all backtrace
thread apply all backtrace full
```

This will generate a file in curren directory *gdb.txt* that can provide some information of what was running in the moment of the crash.

Thanks a lot for your time!

**Comment by Kaian** [comment] 2016-04-28 10:08
Hi @blessendor 

If you have time, try updating to sngrep 1.3.1 (already packaged for debian Jessie) and see if the problem still persist.

We have recently fixed some crashes, maybe related to this issue.

Thanks!

**Comment by Kaian** [comment] 2016-05-19 22:17
Closed due to lack of activity.

Feel free to reopen if the problem still persists in version 1.3.1. I'm quite interested in fixing all posible crashes.

Thanks!

**Closed by Kaian** 2016-05-19 22:17 UTC
Labels: bug, crash
