### ISSUE TITLE
don'nt captrue sip with all nic interface from new release

### ISSUE THREAD

**Issue by michael2009** [irontec/sngrep#87] opened 2016-01-26 15:22 UTC
don'nt captrue sip with all nic interface from new release

confirm issue with  d541c14ba561e80901618ad106edfbb753140a01
Fix payload len for IP assembled packets
Kaian committed on 15 Oct 2015

**Comment by michael2009** [comment] 2016-01-26 15:24
evenif don'nt work with  'sngrep -d any port 5060'

**Comment by Kaian** [comment] 2016-01-26 15:44
Hi @michael2009 

That commit is from 3 months ago and affects both 1.1.0 and 1.2.0 releases.

Can you provide a pcap file where captured packets with some network sniffer are not displayed in sngrep?

Also, the _all_ interface implementation is part of *libpcap*,  there's not much we can do :(.

Thanks for reporting!

**Comment by michael2009** [comment] 2016-01-27 00:59
centos7 x64
libpcap-devel-1.5.3-8.el7.x86_64
libpcap-1.5.3-8.el7.x86_64

nic port:  eth0 , eth1

if  run '/usr/bin/sngrep'  then only cap eth0 with 1.10 or 1.2.0 . then must "sngrep -d eth1"
no work for eth1 if try "sngrep -d any"

but really default work all nic interface with 1.0.0 version

**Comment by Kaian** [comment] 2016-01-27 10:40
Hi @michael2009 

Can you reproduce this problem if you capture packets for **all interfaces** with another capture tool (like tcpdump or ngrep) to a pcap file and you open that file with sngrep?

I can undo that commit in a new branch just for testing purposes, but a pcap would be awesome.

Thanks

**Comment by michael2009** [comment] 2016-01-28 03:30
same issue at all my centos7 x64 with new version . but no issue with 1.0.0 
you can check with sngrep with multi nic . and nic eth1 for sip calls , then you undertsnad

**Comment by Kaian** [comment] 2016-01-28 12:49
Hi @michael2009 

I am still unable to reproduce this but I have undo the commit you mention in branch `issue_87` just for testing.

Could you please try that branch if that solves the problem?

Thanks in advance

**Comment by michael2009** [comment] 2016-01-29 11:57
checked . work fine with branch issue_87

**Comment by Kaian** [comment] 2016-01-29 12:15
Thanks for taking the time to test it!

This problem is related with the line of code that fixes #67 (that you also reported!)
Sorry for insisting, but as checked, this problem can be reproduce with a pcap file. 

With issue_87 branch, the problem with the ACK message of #67 is back again (tested with the pcap you provided for that issue).

Could you capture two dialogs with ngrep or tcpdump and provide a pcap that don't display both with sngrep `master` but works ok with `issue_87` branch?

The goal is to fix both #87 and #67 :)

Thanks for your time.

**Comment by michael2009** [comment] 2016-01-30 02:59
checked branch issue_87 . reproduce issue #67 . loss ACK

**Comment by Kaian** [comment] 2016-02-01 17:50
Hi @michael2009 !

Can you please pull and test again `issue_87`. 
I've made a change in capture IP length code. Also merged some commits from `master`.

Both #67 and #87 should be fixed now

Thanks!

**Comment by michael2009** [comment] 2016-02-02 00:42
checked . seem solved

**Comment by Kaian** [comment] 2016-02-02 10:22
Nice! thanks @michael2009 you rock :)

**Closed by Kaian** 2016-02-02 10:22 UTC
Labels: bug
