### ISSUE TITLE
dragonfly build fail within capture.c

### ISSUE THREAD

**Issue by jungle-boogie** [irontec/sngrep#92] opened 2016-02-03 05:38 UTC
Hello,

DragonFlyBSD is like freebsd but they diverged sometime around 4.4 and do things a bit differently. One differences is they don't use clang:

``` 
% cc --version
cc 5.3.1 [DragonFly] Release/2015-12-04
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

config options:
```
./configure --with-pcre --with-openssl --enable-eep --enable-ipv6 \
CFLAGS=-I/usr/local/include LDFLAGS=-L/usr/local/lib
```

Build fail:
```
Making all in src
make  all-am
  CC       capture.o
capture.c: In function 'capture_init':
capture.c:79:38: error: 'PTHREAD_MUTEX_RECURSIVE_NP' undeclared (first use in this function)
     pthread_mutexattr_settype(&attr, PTHREAD_MUTEX_RECURSIVE_NP);
                                      ^
capture.c:79:38: note: each undeclared identifier is reported only once for each function it appears in
capture.c: In function 'capture_last_error':
capture.c:851:1: warning: type of 'cap' defaults to 'int' [-Wimplicit-int]
 capture_last_error(cap)
 ^
*** Error code 1

Stop.
make[2]: stopped in /home/sean/bin/sngrep/src
*** Error code 1

Stop.
make[1]: stopped in /home/sean/bin/sngrep/src
*** Error code 1

Stop.
make: stopped in /home/sean/bin/sngrep
```

Sorry to bring so many issues up and not offer a solution. :( I just don't know C

**Comment by Kaian** [comment] 2016-02-03 10:14
Hi @jungle-boogie 

For the first error, there should be a matching define that doesn't use the non-portable (_NP) version of threads attributes that is not working as expected.

The second error is caused by bad coding. The function capture_last_error doesn't define the type of the parameter cap (in fact, that parameter shouldn't even exist).

I'll try to prepare a testing environment with DragonFlyBSD installed to test further errors.
Also don't worry at all for reporting! I'll try to make sngrep compatible with most of unix like systems and you help testing with the ones we don't usually use in our daily basis.

Thanks!

**Comment by Kaian** [comment] 2016-02-04 11:47
I have tested the above commits and seems to work without warnings on a fresh DragonFlyBSD.
I have to add the location of **form.h** includes as they seem to be in a different location than the rest of the systems.

```
./configure --with-pcre --with-openssl --enable-eep --enable-ipv6 CFLAGS="-I/usr/local/include -I/usr/local/include/ncurses" LDFLAGS=-L/usr/local/lib
```

Currently I add some checks during configure to search libncurses, libmenu, libpanel, and libform. Maybe I should also add checks for the corresponding header files.

**Comment by jungle-boogie** [comment] 2016-02-04 16:33
hi @Kaian,

That does build on dragonfly now! Thanks for working on this so quickly!

**Comment by Kaian** [comment] 2016-02-04 16:40
Nice!

Closing then :)

**Closed by Kaian** 2016-02-04 16:40 UTC
Labels: bug
