### ISSUE TITLE
Decode IPSec packets in sngrep

### ISSUE THREAD

**Issue by rgmaddi80** [irontec/sngrep#386] opened 2021-12-20 09:56 UTC
Is there a plan to implement decoding of ESP IPSec packets (which carry SIP) in the sngrep utility?

**Comment by Kaian** [comment] 2021-12-20 10:04
Could this be a duplicate of #101 ?

**Comment by Kaian** [comment] 2021-12-20 10:15
That's a quite old issue, but we're keeping the statements there. We prefer to focus on stability and use any spare time in other improvements.

Thanks!

**Closed by Kaian** 2021-12-20 10:15 UTC
