### ISSUE TITLE
Warnings during compile and pcre not found - FreeBSD 10.2-RELASE

### ISSUE THREAD

**Issue by dunst0** [irontec/sngrep#88] opened 2016-01-28 09:20 UTC
Trying to compile latest master on FreeBSD 10.2-RELASE but can not use pcre.

```
checking pcre.h usability... no
checking pcre.h presence... no
checking for pcre.h... no
configure: error:  You need libpcre development files installed to compile with pcre support.
```

```
# find / -name "pcre.h"
/usr/local/include/pcre.h
```

While compiling without pcre i got this warning:
```
  CC       capture.o
capture.c:816:20: warning: implicit declaration of function 'basename' is invalid in C99 [-Wimplicit-function-declaration]
            return basename(capinfo->infile);
                   ^
capture.c:816:20: warning: incompatible integer to pointer conversion returning 'int' from a function with result type 'const char *' [-Wint-conversion]
            return basename(capinfo->infile);
                   ^~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by Kaian** [comment] 2016-01-28 11:12
Hi @dunst0 

For the pcre issue, I am unable to reproduce the problem. I have isntalled a fresh FreeBSD 10.2 and it seems to find pcre.h include

```
root@freebsd:/usr/src/sngrep # ./configure --with-pcre | grep pcre
checking pcre.h usability... yes
checking pcre.h presence... yes
checking for pcre.h... yes
checking for pcre_exec in -lpcre... yes
root@freebsd:/usr/src/sngrep # find / -name "pcre.h"
/usr/local/include/pcre.h
```

The compiler should be checking that path for include files...
```
root@freebsd:/usr/src/sngrep # `gcc -print-prog-name=cc1plus` -v
ignoring nonexistent directory "/usr/local/lib/gcc48/gcc/x86_64-portbld-freebsd10.1/4.8.5/../../../../../x86_64-portbld-freebsd10.1/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/lib/gcc48/include/c++/
 /usr/local/lib/gcc48/include/c++//x86_64-portbld-freebsd10.1
 /usr/local/lib/gcc48/include/c++//backward
 /usr/local/lib/gcc48/gcc/x86_64-portbld-freebsd10.1/4.8.5/include
 /usr/local/include
 /usr/local/lib/gcc48/gcc/x86_64-portbld-freebsd10.1/4.8.5/include-fixed
 /usr/include
End of search list.
```

Fot the basename warning, it's actually an error. It seems there are two different basename functions (GNU and POSIX). I was using the GNU version (included in string.h) but it seems the POSIX way is more compatible :). Anyway the commit with the basename should be in experimental branch, my fault.

**Comment by jungle-boogie** [comment] 2016-01-28 16:19
Hi @Kaian,

For your 10.2 system to find the pcre.h, did you install any additional packages?

**Comment by Kaian** [comment] 2016-01-28 16:40
From the base fresh install, according to the shell history

``` 
pkg install git
cd /usr/src/
git clone http://github.com/irontec/sngrep
cd sngrep/
pkg install autoconf
pkg install automake
pkg install gcc
pkg install pcre
./bootstrap.sh
./configure --with-pcre
make
```

**Comment by dunst0** [comment] 2016-01-28 17:09
@Kaian I didn't installed gcc and was using clang

**Comment by Kaian** [comment] 2016-01-28 17:16
Confimed, this problem is related with clang.

```
# CC=clang ./configure --with-pcre
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for new_item in -lmenu... yes
checking pcre.h usability... no
checking pcre.h presence... no
checking for pcre.h... no
configure: error:  You need libpcre development files installed to compile with pcre support.
``` 

Somehow clang doesn't look into /usr/local for includes and libraries properly. I don't know if this is a common problem, but as a workaround you can set include/library paths from configure.

```
# CC=clang CFLAGS=-I/usr/local/include LDFLAGS=-L/usr/local/lib ./configure --with-pcre
```

**Comment by jungle-boogie** [comment] 2016-01-28 17:26
Hi @Kaian,

Yes, with you telling clang the specific path, sngrep will build. 

```
CFLAGS=-I/usr/local/include LDFLAGS=-L/usr/local/lib ./configure --with-pcre --with-openssl
````
That will also build against libressl:

```
/usr/local/bin/sngrep:
        libpcre.so.1 => /usr/local/lib/libpcre.so.1 (0x80084a000)
        libcrypto.so.35 => /usr/local/lib/libcrypto.so.35 (0x800abf000)
        libssl.so.35 => /usr/local/lib/libssl.so.35 (0x800ebd000)
        libmenu.so.5 => /usr/lib/libmenu.so.5 (0x801123000)
        libform.so.5 => /usr/lib/libform.so.5 (0x80132a000)
        libpanel.so.5 => /usr/lib/libpanel.so.5 (0x801539000)
        libncurses.so.8 => /lib/libncurses.so.8 (0x80173c000)
        libpcap.so.8 => /lib/libpcap.so.8 (0x801989000)
        libthr.so.3 => /lib/libthr.so.3 (0x801bce000)
        libc.so.7 => /lib/libc.so.7 (0x801df2000)
````

**Comment by Kaian** [comment] 2016-01-28 18:05
It seems its only a problem with clang default include paths in FreeBSD

https://wiki.freebsd.org/WarnerLosh/UsrLocal

**Comment by Kaian** [comment] 2016-02-01 17:55
I'll close this issue because the clang includes seems something local to FreeBSD installations.
I'm not sure about overriding the default include path of the compiler, but any information related with other softwares workaround will be appreciated.

**Closed by Kaian** 2016-02-01 17:55 UTC
Labels: bug
