### ISSUE TITLE
RTP flow view incorrect .

### ISSUE THREAD

**Issue by michael2009** [irontec/sngrep#108] opened 2016-03-26 15:52 UTC
When sip server RX/TX  RTP with loopback interface 127.0.0.1 then flow view incorrect .

**Comment by Kaian** [comment] 2016-03-29 13:41
Hi michael,

I don't have an enviroment setup to test this issue. Could you provide an screenshot, or even better a pcap so I can debug it?.

Thanks for reporting one more time :)

**Comment by michael2009** [comment] 2016-03-29 14:05
total 3 calls .
You can select first 1,2 INIVTE  , and Enter . then show flow

**Comment by Kaian** [comment] 2016-04-04 08:55
Hi!

Did you send me a pcap for this issue?  Sorry I haven't received anything :(

Thanks for your efforts michael!

**Comment by Kaian** [comment] 2016-04-04 11:08
Hi @michael2009 

Thanks for the test pcap file one more time :)
The attached image shows what I see in my local sngrep build. This seems correct to me, _the arrow_ is displayed only with a direction because source and destination are the same.

Is this incorrect? Do you think there's a better way to displayer src == dst arrows only using one column?

Best regards,
![ss108](https://cloud.githubusercontent.com/assets/800069/14246274/5f4b0c88-fa66-11e5-946f-9a6cbce759ff.png)

**Comment by michael2009** [comment] 2016-04-04 14:40
Hi kaian , 

found three issue .

1. putty resize tty console 
2. don'nt show both leg RTP arrow . pcap file , select dialog idx 9
 

 
3 . don'nt show rtp .  pcap file , select dialog idx 7
 

 
------------------ Original ------------------

**Comment by Kaian** [comment] 2016-04-04 15:08
Hello!

_1. putty resize tty console_
Only Call List resizes. Call Flow has no resize logic. Not a bug, it lacks implementation.

_2. don'nt show both leg RTP arrow . pcap file , select dialog idx 9_
RTP streams can only belong to a single dialog. Stream using ports 3040 <-> 4031 in your pcap file was being used by dialog 8. I have a change to use the last dialog and not the first found, so the displayed data is more similar to the one displayed in wireshark.

_3 . don'nt show rtp .  pcap file , select dialog idx 7_
Idx 7 has SDP addresses 192.168.xxx.xxx:11780 and 54.222.xxx.xxx:1037.
The pcap file has no RTP packet with that addresses, so this dialog has no RTP streams.
Check it in wireshark.

**Comment by Kaian** [comment] 2016-04-04 19:02
Hi!

I've received now the images of the issues you mention on my mail! In fact the first one was Call List, so I have changed a bit how this screen resizes.

Thanks for reporting!

**Comment by Kaian** [comment] 2016-05-02 14:39
I'm closing this issue because it has too many topics (rtp flows/resize/etc).

Feel free to reopen a new issue in any of the not fixed problems described here.

Thanks!

**Closed by Kaian** 2016-05-02 14:39 UTC
