### ISSUE TITLE
White Highlited data not readable

### ISSUE THREAD

**Issue by dipenpatel235** [irontec/sngrep#230] opened 2018-01-11 12:48 UTC
hello..
i have attached screenshot of sngrep.
that is SUBSCRIBE message detail.
in that i am not able to read White Highlighted data.
so it is corrupted data or Encrypted data ?

![untitled](https://user-images.githubusercontent.com/8135097/34826197-a2852d38-f6fb-11e7-8bf2-8ae20d5c1d21.png)

Thanks

**Comment by Kaian** [comment] 2018-01-11 15:15
Hi @dipenpatel235 !

Payload preview prints packet content byte by byte and currently only supports ascii characters.

This is usually not a problem for classic SDP body contents in SIP (although supporting UTF-8 will be implement if a new mayor version is coded), but binary contents can not be displayed correctly. I assume by your SIP headers that your contents are compressed, so there are printed that way.

I can implement a quick fix that prints all non-ascii bytes as a generic character (for example dot `.`) to avoid that glichy output.

By the way, you can properly see lines for arrows and columns if you change your putty's character set (Windows -> Translarion -> Remote Character Set)

Thanks for reporting!

**Comment by Kaian** [comment] 2018-02-28 20:56
I will mark as duplicate of #211

**Closed by Kaian** 2018-02-28 20:56 UTC
